delete functionality added, cascade in models
Lnola/StepByStep pull request #14
Opened 2023-01-09 16:20 UTC by js53110

## SUMMARY

### Type of change
- **Feature**
### Description
Detete functionality
#### Why is it needed?
- user must be able to delete his own recipes

- changes in "card" and "viewRecipes" components ("deletable" bool variable to declare if card can or cannot be deleted)
- delete button on card that calls function from "deleteRecipe.js", which is located in scripts folder
- deleteRecipe.js with a function that calls "recipesApi" to delete a recipe, sends "recipeId" through body
- modification in some models to allow cascading when deleting rows from database
- new function in "recipe.controller" (delete)
#### What does it do?
Removes wanted recipe from database

2023-01-09 16:24 UTC, js53110 commented on server/src/recipe/index.js
> +
unwanted new line, will change

2023-01-17 18:35 UTC, Lnola requested changes

2023-01-17 18:35 UTC, Lnola commented on client/src/api/recipes.js
> +  get deleteRecipe() {
just delete would be better

2023-01-17 18:35 UTC, Lnola commented on client/src/api/recipes.js
> +const deleteRecipe = recipeId => {
delete

2023-01-17 18:35 UTC, Lnola commented on server/src/recipe/recipe.controller.js
> +    });
```js
const recipe = await Recipe.findByPk(recipeId)
```

2023-01-17 18:35 UTC, Lnola commented on server/src/recipe/recipe.controller.js
> +  const recipeId = await req.body.recipeId;
no need for await

2023-01-17 18:35 UTC, Lnola commented on server/src/recipe/recipe.controller.js
> +    return next(new Error());
new HttpError(error code, error message)

2023-01-17 18:35 UTC, Lnola commented on server/src/recipe/recipe.controller.js
> +      return res.status(OK).send();
res.sendStatus(OK)

2023-01-17 18:35 UTC, Lnola commented on client/src/api/recipes.js
> +};
the backend sends nothing back so you don't need to extract data here

2023-01-17 18:35 UTC, Lnola commented on client/src/components/common/Card.svelte
> +    <button class="circle deleteButton" on:click={deleteRecipe(id)}><i class="fa-solid fa-trash" /></button>
card doesn't know it's displaying a recipe so importing something called deleteRecipe that deletes a recipe makes no sense in a card context. The card can emit/dispatch a action on button click and the parent catches the dispatched message and acts on it by deleting a recipe, ingredient or whatever else the card is about

2023-01-17 18:35 UTC, Lnola commented on client/src/components/common/Card.svelte
> +    left: 83%;
fixed values work better for absolute elements

2023-01-17 18:35 UTC, Lnola commented on client/src/utils/scripts/deleteRecipe.js
> +}
this can be defined in the RecipesUser.svelte, doesn't need to be a script

2023-01-17 18:35 UTC, Lnola commented on server/src/recipe/index.js
> +  .post('/delete', deleteRecipe)
`.delete` and not `.post`

also, can you sort these so they are get -> post -> delete

2023-01-17 18:35 UTC, Lnola commented on server/src/recipe/recipe.controller.js
> +    if (recipe) {
you need to let the user know that they are trying to delete something that doesnt exist

```js
if(!recipe) return new HttpError(NOT_FOUND, not found message)
await recipe.destroy()...
```

2023-01-17 18:39 UTC, Lnola commented on client/src/utils/scripts/deleteRecipe.js
> +    redirect('UserRecipes');
just update the recipes array, you don't need to refresh the page

2023-01-18 11:34 UTC, merged